name: Run tests

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

jobs:
  test-sg-otio:

    name: "sg-otio"
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest] # windows-latest when wheel is in place
    env:
      SG_TEST_SITE: https://gpltechdemos.shotgunstudio.com
      SG_TEST_SCRIPT_NAME: otio_tests
      # Set as a secret on the repository
      SG_TEST_SCRIPT_KEY: ${{ secrets.SG_TEST_SCRIPT_KEY }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install Package
        run: |
          pip install -e .
          pip install -e .[dev]

      - name: Lint with flake8
        run: |
          flake8 --show-source --statistics

      - name: Test with pytest
        run: |
          pytest

        shell: bash
