# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the SG Otio project

name: Run tests

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

jobs:
  test-sg-otio:

    name: "sg-otio"
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11']
        os: [ubuntu-latest, macos-latest] # windows-latest when wheel is in place

    runs-on: ${{ matrix.os }}

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      GH_COV_PY: 3.9
      GH_COV_OS: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/shotgunsoftware/python-api.git

      - name: Install Package
        run: |
          pip install -e .
          pip install -e .[dev]  # Why 2 pip installs?

      - name: Lint with flake8
        run: |
          flake8 --show-source --statistics --config .flake8

      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest -s --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        if: matrix.python-version == env.GH_COV_PY && matrix.os == env.GH_COV_OS
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: sg-otio-codecov
          fail_ci_if_error: true
          env_vars: OS,PYTHON

#        shell: bash
